- name: Copiando arquivo jboss-eap.conf
  copy:
    src: /opt/jboss-eap/bin/init.d/jboss-eap.conf
    dest: /etc/default/jboss-eap.conf
    owner: root
    group: root
    remote_src: yes

- name: Copiando arquivo jboss-eap-rhel
  copy:
    src: /opt/jboss-eap/bin/init.d/jboss-eap-rhel.sh
    dest: /etc/init.d/jboss7
    owner: root
    group: root
    mode: 0755
    remote_src: yes

- name: Setando usuario para start do JBOSS
  lineinfile:
    dest: /etc/default/jboss-eap.conf
    regexp: '# JBOSS_USER=jboss-eap'
    line: 'JBOSS_USER=jboss-eap'

- name: Configurando JBOSS para rodar em modo Domain
  lineinfile:
    dest: /etc/default/jboss-eap.conf
    regexp: '# JBOSS_MODE=standalone'
    line: 'JBOSS_MODE=domain'

- name: Configurando arquivo DOMAIN
  lineinfile:
    dest: /etc/default/jboss-eap.conf
    regexp: '# JBOSS_DOMAIN_CONFIG=domain.xml'
    line: 'JBOSS_DOMAIN_CONFIG=domain.xml'

- name: Configurando arquivo HOSTS
  lineinfile:
    dest: /etc/default/jboss-eap.conf
    regexp: '# JBOSS_HOST_CONFIG=host.xml'
    line: 'JBOSS_HOST_CONFIG=host.xml'


- name: Reiniciando o Daemon
  raw: 'systemctl daemon-reload'

- name: Colocando o servico para iniciar automatico
  service:
    name: jboss7
    enabled: yes
