- name: Instalar Unzip
  yum:
    name:
      - unzip
      - java-1.8.0-openjdk
    state: present

- name: Criar grupo JBOSSRO no Servidor
  group:
    name: jbossro
    state: present

- name: Criando usuario JBOSS no Servidor
  user:
    name: jboss-eap
    group: jbossro
    state: present

- name: Copiando pastas do JBOSS
  unarchive:
    src: /tmp/jboss-eap-7.2.0.zip
    dest: /opt/
    owner: jboss-eap
    group: jbossro

- name: Criar link simbolico para diretorio
  file:
    src: /opt/jboss-eap-7.2
    dest: /opt/jboss-eap
    owner: jboss-eap
    group: jbossro
    state: link

